//go:build linux

package installer

// Linux system integration for the installer: input-device access.
//
// Kernel input isolation (EVIOCGRAB — see crates/platform) needs to read
// /dev/input/event*, which is root:input on most distros. This step makes
// the *desktop user* the owner of those nodes:
//
//   - a udev rule is generated with the user's uid baked in as OWNER, so
//     every present and future input device is owned by that user. This is
//     a plain udev property (supported by udev *and* eudev alike) and needs
//     no logind, no seat magic, no group dance — the kernel assigns
//     ownership when the rule runs, on every systemd and non-systemd
//     distro that has udev rules at all. TAG+="uaccess" is also set so a
//     logind system may additionally grant the active seat user an ACL.
//   - the live /dev/input/event* nodes are chowned *right now*, so a
//     server that is already running gains access within its next
//     re-scan — no re-login, no restart, no supplementary-group semantics
//     (groups only ever apply to processes started after the change; node
//     ownership applies to everything).
//
// Writing to /etc needs root, so the step re-executes this binary through
// pkexec (the desktop's standard privilege prompt — the same one-shot
// consent as Windows UAC). Because bare window managers often run no
// polkit agent, one is started from the known agent list when none is
// found, so the prompt always appears. If no privilege agent exists at
// all the install still succeeds; the server just runs without isolation
// and reports it clearly.

import (
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"time"
)

const rulePath = "/etc/udev/rules.d/99-kvmshare-input.rules"

// grantRule renders the udev rule for one desktop user. The uid is baked
// in as OWNER — the whole mechanism, and the reason no group membership or
// logind session is ever required. `group` is "input" when the system has
// it (the common case) so root keeps rw access too; otherwise the user's
// primary group is used so the node is still group-readable by them.
func grantRule(uid, group string) string {
	return fmt.Sprintf(`# kvmshare: grant the installing desktop user (uid %s) access to the
# physical input devices so the server can isolate them (kernel input
# isolation, EVIOCGRAB) while the shared cursor is on another machine.
# Generated by the kvmshare installer on every install/update; removed on
# uninstall. Plain udev properties — works with udev and eudev, with or
# without logind.
KERNEL=="event*", SUBSYSTEM=="input", OWNER="%s", GROUP="%s", MODE="0660", TAG+="uaccess"
`, uid, uid, group)
}

// The user who asked for elevation. pkexec sets PKEXEC_UID; sudo sets
// SUDO_UID; a root shell leaves both empty and the current root user is
// the only sensible fallback (the caller should have told us otherwise).
func elevatingUser() (*user.User, error) {
	for _, env := range []string{"PKEXEC_UID", "SUDO_UID"} {
		if v := os.Getenv(env); v != "" && v != "0" {
			if u, err := user.LookupId(v); err == nil {
				return u, nil
			}
			if name, err := exec.Command("id", "-nu", v).Output(); err == nil {
				if u, err := user.Lookup(strings.TrimSpace(string(name))); err == nil {
					return u, nil
				}
			}
		}
	}
	return user.LookupId(strconv.Itoa(os.Getuid()))
}

// integrateDesktop runs after a successful install: grant input access.
// Failure is a warning, never an install failure — without the rule the
// software still works, only raw-event leaks to raw-reading apps remain.
func integrateDesktop(dir string) error {
	return EnsureInputAccess()
}

// IsElevated reports whether this process can write privileged system
// locations (root). The Linux uninstall already falls back gracefully
// without it, so this only drives Windows' self-elevation; Linux keeps
// its existing best-effort behavior.
func IsElevated() bool {
	return os.Geteuid() == 0
}

// SelfElevate is a no-op on Linux: the uninstall keeps its existing
// behavior (user files always removed; the udev rule removed when run
// with privileges).
func SelfElevate([]string) error { return nil }

// ensureInputAccess is the --input-access entry point and the post-install
// step. Grant-only-if-missing, self-elevating: installs, updates, GUI
// startups and `make install` may call it unconditionally — it stays
// silent forever once access exists and prompts at most once when it
// does not.
//
// The probe depends on who is asking: before elevation it tries to open
// the devices as the real user; as root (the pkexec re-exec) it inspects
// node ownership against the elevating user, because root can open
// anything and an open-based probe would always answer "granted".
func ensureInputAccess() error {
	if os.Geteuid() == 0 {
		u, err := elevatingUser()
		if err != nil {
			return fmt.Errorf("resolve desktop user: %w", err)
		}
		uid, err := strconv.Atoi(u.Uid)
		if err != nil {
			return fmt.Errorf("parse uid %s: %w", u.Uid, err)
		}
		if grantedFor(uid) {
			fmt.Println("kvmshare-install: input access already granted")
			return nil
		}
		if err := integrateInputAccess(); err != nil {
			return err
		}
		fmt.Println("kvmshare-install: input access granted")
		return nil
	}
	if inputAccessGranted() {
		return nil // already granted — stay silent, never re-prompt
	}
	return integrateViaPkexec()
}

// grantedFor reports whether every input device node is readable by uid:
// owned by them, or world-readable (mode has the other-read bit). This
// is the root-side probe — see [`ensureInputAccess`].
func grantedFor(uid int) bool {
	nodes, err := filepath.Glob("/dev/input/event*")
	if err != nil || len(nodes) == 0 {
		return true
	}
	for _, node := range nodes {
		var st syscall.Stat_t
		if err := syscall.Stat(node, &st); err != nil {
			continue
		}
		if int(st.Uid) == uid {
			continue
		}
		if st.Mode&0o004 != 0 {
			continue // world-readable: anyone can read it
		}
		return false
	}
	return true
}

// inputAccessGranted reports whether the current user can already read
// every physical input device. Used so installs, updates and GUI startups
// re-run the grant step without ever re-prompting once access exists.
// With no devices present there is nothing to grant.
func inputAccessGranted() bool {
	nodes, err := filepath.Glob("/dev/input/event*")
	if err != nil || len(nodes) == 0 {
		return true
	}
	for _, node := range nodes {
		f, err := os.OpenFile(node, os.O_RDONLY, 0)
		if err != nil {
			return false
		}
		f.Close()
	}
	return true
}

// removeDesktopIntegration undoes integrateDesktop (used by --uninstall).
func removeDesktopIntegration(dir string) error {
	if os.Geteuid() != 0 {
		// Best-effort without elevation: leave the rule (harmless) but
		// report nothing — uninstall of the user's files already worked.
		return nil
	}
	return os.Remove(rulePath)
}

// launchGUI is a no-op on Linux (the GUI is launched from the desktop
// entry; main.go prints the command).
func launchGUI(string) error { return nil }

// integrateViaPkexec re-executes this installer as root with
// --input-access, so the user consents through the desktop's standard
// privilege prompt instead of a shell command.
func integrateViaPkexec() error {
	exe, err := os.Executable()
	if err != nil {
		return fmt.Errorf("input access not granted: %v", err)
	}
	if _, err := exec.LookPath("pkexec"); err != nil {
		return fmt.Errorf("input access not granted (no pkexec on this system): %v", err)
	}
	// Bare window managers (i3, sway, ...) usually run no polkit agent, so
	// a pkexec call would die with "no authentication agent". Start one
	// from the platform's known agents for the duration of the prompt.
	stop := startAuthAgentIfNeeded()
	if stop != nil {
		defer stop()
	}
	cmd := exec.Command("pkexec", exe, "--input-access")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("input access not granted (privilege prompt declined or unavailable?): %v: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// polkitAgents are the common desktop authentication agents, in order of
// preference. The first that exists and is not already running is started
// so the pkexec prompt has somewhere to appear.
var polkitAgents = []string{
	"polkit-gnome-authentication-agent-1",
	"xfce-polkit",
	"lxpolkit",
	"mate-polkit",
	"lxsession",
}

// startAuthAgentIfNeeded returns a stop func when it started an agent,
// or nil when an agent is already running / none can be started.
func startAuthAgentIfNeeded() func() {
	// Any agent process already up?
	ps, err := exec.Command("pgrep", "-f", "authentication-agent|polkit.*agent|lxpolkit|xfce-polkit|mate-polkit").Output()
	if err == nil && strings.TrimSpace(string(ps)) != "" {
		return nil // an agent is running — pkexec will use it
	}
	paths := append([]string(nil), polkitAgents...)
	// Also look in the standard libexec dirs where distros hide agents.
	for _, d := range []string{"/usr/libexec", "/usr/lib/polkit-1", "/usr/lib/x86_64-linux-gnu"} {
		for _, a := range polkitAgents {
			if _, err := os.Stat(filepath.Join(d, a)); err == nil {
				paths = append(paths, filepath.Join(d, a))
			}
		}
	}
	var agent string
	for _, a := range paths {
		if p, err := exec.LookPath(a); err == nil {
			agent = p
			break
		} else if strings.Contains(a, "/") {
			if _, err := os.Stat(a); err == nil {
				agent = a
				break
			}
		}
	}
	if agent == "" {
		return nil
	}
	cmd := exec.Command(agent)
	if err := cmd.Start(); err != nil {
		return nil
	}
	// Give the agent a moment to register with polkitd before pkexec runs.
	time.Sleep(700 * time.Millisecond)
	return func() { _ = cmd.Process.Kill() }
}

// integrateInputAccess runs as root (either directly or via pkexec):
// generate and install the per-user udev rule, then make it take effect
// for every device — present ones included — right now.
func integrateInputAccess() error {
	u, err := elevatingUser()
	if err != nil {
		return fmt.Errorf("resolve desktop user: %w", err)
	}
	// The device group: `input` where the system has it (the common
	// case), else the user's primary group so the node still resolves.
	gid := u.Gid
	if g, err := user.LookupGroup("input"); err == nil {
		gid = g.Gid
	}
	uid, err := strconv.Atoi(u.Uid)
	if err != nil {
		return fmt.Errorf("parse uid %s: %w", u.Uid, err)
	}
	g, err := strconv.Atoi(gid)
	if err != nil {
		return fmt.Errorf("parse gid %s: %w", gid, err)
	}
	if err := os.WriteFile(rulePath, []byte(grantRule(u.Uid, gid)), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", rulePath, err)
	}

	// udev re-applies the rule to already-present devices (hotplug and
	// `udevadm trigger`), but systems differ: also chown the live nodes
	// directly so access exists even where trigger is unavailable or
	// delayed. Ownership on a device node applies to processes already
	// running — the running server picks the mouse up on its next rescan,
	// no restart, no re-login.
	nodes, _ := filepath.Glob("/dev/input/event*")
	for _, node := range nodes {
		_ = os.Chown(node, uid, g)
		_ = os.Chmod(node, 0o660)
	}

	// Register the rule for future hotplugs and re-trigger present devices
	// (harmless where udevadm is absent).
	_ = exec.Command("udevadm", "control", "--reload-rules").Run()
	_ = exec.Command("udevadm", "trigger", "--subsystem-match=input").Run()
	return nil
}
