[package]
name = "kvmshare-app"
description = "The kvmshare server and client executables."
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kvmshare-core = { workspace = true }
kvmshare-log = { workspace = true }
kvmshare-protocol = { workspace = true }
kvmshare-platform = { workspace = true }
libc = "0.2"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
fs2 = "0.4.3"
