//! Local input capture via XI2 *raw* events.
//!
//! Why raw events? They carry the device's own motion deltas (sub-pixel
//! fixed-point values), and they are generated only by the physical
//! device — never by programmatic cursor warps. That gives the session
//! two things at once:
//!
//! * **Smoothness**: deltas straight from the driver, accumulated to
//!   whole pixels without losing sub-pixel motion.
//! * **No warp feedback**: when the server parks or moves its hidden
//!   cursor, no phantom motion is produced, so the virtual cursor never
//!   oscillates (the classic KVM bug — see `core::session`).
//!
//! Raw button and key events are delivered to any client selecting them
//! on the root window, so no pointer grab or input window is needed
//! while the cursor is **local** — the desktop keeps working normally.
//!
//! ## While the cursor is on a client
//!
//! This thread also owns every *control* action on the local cursor —
//! pointer/keyboard grab, warp (park/place), and hide/show — through
//! [`CaptureCommand`]s from the engine. Everything sits on **one**
//! connection on purpose: a pointer grab by one client would block warps
//! by another, so the grabber must also be the warper. Grabbing the
//! pointer and keyboard while the cursor is away stops the local desktop
//! from acting on physical input too — without it, clicks and typing
//! would land on **both** machines at once. XI2 raw events are generated
//! from device input before core-event routing, so they keep flowing to
//! this connection regardless of grabs, and the session stays fed.
//!
//! ## Key repeat
//!
//! Raw key events fire only on real device transitions — the X server's
//! auto-repeat is synthesized, not generated by the device, so a held key
//! produces exactly one raw press and one raw release. The local desktop
//! gets repeats natively, but a *client* would see a single press with no
//! repeat. This thread therefore synthesizes repeats for physically held
//! keys (typical OS delay/rate) so holding behaves the same everywhere.
//!
//! ## Motion: coalescing and position beacons
//!
//! Two observations about the motion stream shape the implementation:
//!
//! * **Device rates are wasteful.** A modern mouse reports at up to
//!   1000 Hz; forwarding one message per raw event floods the wire with
//!   tiny frames and makes the cursor jittery whenever the network is
//!   under load (a download, a busy peer). Raw deltas are therefore
//!   accumulated and sent at a fixed cadence ([`MOTION_PERIOD`]) — the
//!   total motion is identical, but the frame rate is capped well above
//!   what the eye can follow.
//! * **Raw deltas are pre-acceleration.** The *visible* cursor moves by
//!   accelerated deltas, so the two drift apart on the local screen. The
//!   capture also selects ordinary XI motion events (the ones carrying
//!   the real, post-acceleration position) and forwards each as a
//!   [`Message::MouseMoveAbs`] *beacon*. The session re-anchors its
//!   virtual cursor to the beacon while on the local screen — zero X
//!   round-trips, purely event-driven. At the screen edge the OS pins the
//!   pointer, motion events stop and raw deltas keep flowing, which is
//!   exactly the outward-push signal that triggers a screen switch.
//!
//! ## Wheel
//!
//! X11 delivers each wheel notch as a button-press **and** a matching
//! button-release. Only the press is a scroll — forwarding both would
//! make every notch scroll twice on the client.

use std::collections::HashMap;
use std::sync::mpsc::{self, Receiver, Sender};
use std::thread;
use std::time::{Duration, Instant};

use x11rb::connection::{Connection, RequestConnection};
use x11rb::protocol::xfixes::{self, ConnectionExt as _};
use x11rb::protocol::xinput::{self, EventMask, Fp3232, XIEventMask};
use x11rb::protocol::xproto::{self, ConnectionExt as _};
use x11rb::protocol::Event as XEvent;
use x11rb::rust_connection::RustConnection;

use kvmshare_log::{log_debug, log_error, log_info, log_warn};
use kvmshare_protocol::message::{KeyKind, Message};

use super::buttons::{self, XButton};
use crate::evdev_reader::EvdevReader;
use crate::keys::ESCAPE_KEY_HID;
use crate::motion::PendingMotion;

/// Device id for "all devices" (XIAllDevices).
const DEVICE_ALL: u16 = 0;

/// When the escape key is consumed we must also swallow its release, or
/// a bare key-up would reach the client (or home) with no matching down.
fn is_escape(key: u32) -> bool {
    key == ESCAPE_KEY_HID
}

/// How long a key must be held before the first synthesized repeat.
const REPEAT_DELAY: Duration = Duration::from_millis(500);
/// Interval between synthesized repeats while a key stays held.
const REPEAT_INTERVAL: Duration = Duration::from_millis(33); // ≈ 30/s

/// Idle poll pause. The capture loop polls for X events instead of
/// blocking, so it can also apply engine commands, forward motion at the
/// capped cadence, and synthesize key repeats while no input is flowing.
/// 2 ms is far below human perception and keeps idle CPU negligible.
const POLL_PAUSE: Duration = Duration::from_millis(2);

/// Minimum gap between forwarded position beacons. Ordinary XI motion
/// events arrive at the device's report rate (up to 1000 Hz on a modern
/// mouse); forwarding every one floods the wire and the session channel
/// with near-identical positions, and under load the backlog makes every
/// beacon *stale* — the session then re-anchors to old positions, which
/// delays the edge-park confirmation and makes crossings hesitate.
/// Beacons are therefore coalesced like motion: only the newest position
/// is kept and sent at this cadence, so a beacon is never older than one
/// period plus the poll pause, and the stream costs a few frames per
/// second instead of a thousand.
const BEACON_PERIOD: Duration = Duration::from_millis(6);

/// A control action the engine wants performed on the local cursor.
///
/// These arrive over a channel and are executed on the *capture*
/// connection. That single-connection rule is what lets the same client
/// grab the pointer and still warp it (warps from a different client are
/// not honored while another client holds the grab).
#[derive(Debug, Clone, Copy)]
pub enum CaptureCommand {
    /// Grab (or release) the pointer and keyboard so local windows do not
    /// act on physical input while the cursor is on a client.
    Grab(bool),
    /// Isolate (or release) the physical input devices from the local
    /// desktop entirely — the evdev reader takes over. Stronger than
    /// [`CaptureCommand::Grab`]: it also stops *raw* event delivery to
    /// apps that read XI2 raw events (browsers, smooth-scroll
    /// terminals), which no X grab can suppress. No-op when evdev is
    /// unavailable (the grab-only fallback).
    IsolateRemote(bool),
    /// Warp the local cursor to (x, y) — parking it, re-centering it, or
    /// placing it at the entry point when control returns home.
    Warp(i32, i32),
    /// Hide/show the local cursor (XFixes).
    CursorVisible(bool),
}

/// Select XI2 raw events on `root`.
///
/// **Mask encoding gotcha (verified against the X server source):**
/// `mask_len` counts 4-byte words, but the mask bits are byte-packed
/// (event `j` lives at byte `j/8`, bit `j%8`). x11rb serializes each
/// `XIEventMask` as one native `u32` word, which produces exactly the
/// right bytes — as long as every wanted bit is OR'd into a **single**
/// word. Passing one `XIEventMask` per event instead puts each bit in
/// its own word and silently selects nothing.
fn select_input_events(conn: &RustConnection, root: xproto::Window) -> Result<(), String> {
    let mut word = 0u32;
    for bit in [
        // Raw events: device deltas / buttons / keys (warp-free).
        XIEventMask::RAW_MOTION,
        XIEventMask::RAW_BUTTON_PRESS,
        XIEventMask::RAW_BUTTON_RELEASE,
        XIEventMask::RAW_KEY_PRESS,
        XIEventMask::RAW_KEY_RELEASE,
        // Ordinary motion: the real, post-acceleration pointer position
        // (used as a resync beacon for the session).
        XIEventMask::MOTION,
    ] {
        word |= u32::from(bit);
    }

    xinput::xi_select_events(&conn, root, &[EventMask { deviceid: DEVICE_ALL, mask: vec![XIEventMask::from(word)] }])
        .map_err(|e| format!("xi_select_events: {e}"))?
        .check()
        .map_err(|e| format!("xi_select_events reply: {e}"))?;
    conn.flush().map_err(|e| format!("X11 flush: {e}"))?;
    Ok(())
}

/// 32.32 fixed point → f64.
fn fp_to_f64(v: &Fp3232) -> f64 {
    v.integral as f64 + v.frac as f64 / 4294967296.0
}

/// Extract the Rel X / Rel Y motion from a raw event.
///
/// XI2 raw events carry `axisvalues_raw` for **only** the axes whose
/// bits are set in `valuator_mask` — so positional indexing is wrong for
/// any device with more than two valuators (a mouse that also reports
/// scroll axes as valuators, a touchpad, a knob, …). A wheel notch on
/// such a device can arrive as a raw *motion* whose first value is the
/// scroll delta (e.g. ±120), which, taken as dx, shoves the cursor
/// sideways and eventually past the screen edge — the cause of
/// "scrolling moves the cursor" and phantom boundary jumps.
///
/// This walks the mask, pairs each set bit with its value in order, and
/// keeps only axes 0 (Rel X) and 1 (Rel Y). Everything else — scroll
/// deltas included — is never cursor motion. Wheel input on devices that
/// deliver it as valuators instead of buttons is a separate concern;
/// devices we have seen report wheel through buttons 4-7, which the
/// button path already turns into [`Message::MouseWheel`].
fn raw_xy(mask: &[u32], values: &[Fp3232]) -> (f64, f64) {
    let mut dx = 0.0;
    let mut dy = 0.0;
    let mut idx = 0usize;
    for (word_i, word) in mask.iter().enumerate() {
        for bit in 0..32 {
            if word & (1 << bit) != 0 {
                if let Some(v) = values.get(idx) {
                    let v = fp_to_f64(v);
                    match word_i * 32 + bit {
                        0 => dx = v,
                        1 => dy = v,
                        _ => {}
                    }
                }
                idx += 1;
            }
        }
    }
    (dx, dy)
}

/// Repeat state for one physically held key.
struct Held {
    down_at: Instant,
    last_repeat: Instant,
}

/// Captures local input and controls the local cursor on a background
/// thread. Owns its X connection exclusively — the engine talks to it
/// only through [`CaptureCommand`]s, and the clipboard/position queries
/// use the engine's own separate connection.
struct InputCapture {
    conn: RustConnection,
    root: xproto::Window,
    tx: Sender<Message>,
    cmd_rx: Receiver<CaptureCommand>,
    motion: PendingMotion,
    /// The newest real pointer position seen but not yet forwarded as a
    /// beacon (coalesced to [`BEACON_PERIOD`]; see the const docs).
    beacon: Option<(i32, i32)>,
    /// When the last beacon was sent (rate limiter).
    last_beacon: Option<Instant>,
    /// Keys the device has pressed but not yet released (HID usage → state).
    held: HashMap<u32, Held>,
    /// Whether *we* currently hold the pointer+keyboard grab.
    grabbed: bool,
    /// Kernel-level device isolation while the cursor is on a client.
    /// Always present; it engages the moment `/dev/input` becomes
    /// readable (grab-only until then).
    evdev: EvdevReader,
}

/// Open the X display (`None` = `$DISPLAY`), select XI2 raw events on the
/// root window, and start the capture thread.
///
/// Returns the channel the server's main loop reads local input from.
/// `cmd_rx` delivers the engine's cursor-control commands.
pub fn start(display: Option<&str>, cmd_rx: Receiver<CaptureCommand>) -> Result<Receiver<Message>, String> {
    let (conn, screen_num) = RustConnection::connect(display).map_err(|e| format!("X11 connect: {e}"))?;
    let root = conn.setup().roots[screen_num].root;

    // XI2 handshake (raw events need server XI >= 2.0).
    let version = xinput::xi_query_version(&conn, 2, 0).map_err(|e| format!("XI2 query: {e}"))?.reply().map_err(|e| format!("XI2 reply: {e}"))?;
    if version.major_version < 2 {
        return Err(format!("XI2 required, server has XI {}.{}", version.major_version, version.minor_version));
    }

    select_input_events(&conn, root)?;
    // XFixes is needed for cursor hide/show (also used by the engine).
    if conn.extension_information(xfixes::X11_EXTENSION_NAME).map_err(|e| format!("XFixes query: {e}"))?.is_none() {
        return Err("XFixes extension not available".into());
    }
    conn.xfixes_query_version(5, 0).map_err(|e| format!("XFixes version: {e}"))?;
    log_info!("input capture started (XI2 raw events)");

    let (tx, rx) = mpsc::channel();
    // The evdev reader is always started; it isolates the devices at the
    // kernel the moment they become readable. Until then the server runs
    // grab-only (raw-reading apps may react to forwarded input).
    let evdev = EvdevReader::start(tx.clone());
    let capture = InputCapture {
        conn,
        root,
        tx,
        cmd_rx,
        motion: PendingMotion::default(),
        beacon: None,
        last_beacon: None,
        held: HashMap::new(),
        grabbed: false,
        evdev,
    };
    thread::spawn(move || {
        if let Err(e) = capture.run_forever() {
            log_error!("input capture stopped: {e}");
        }
    });
    Ok(rx)
}

impl InputCapture {
    /// The capture loop: drain X events, apply engine commands, forward
    /// coalesced motion and synthesized key repeats at their cadences,
    /// and pause briefly so the thread stays responsive to all of it even
    /// when nothing else is happening. Runs forever; returns only on a
    /// fatal X error.
    fn run_forever(mut self) -> Result<(), String> {
        loop {
            loop {
                match self.conn.poll_for_event() {
                    Ok(Some(ev)) => self.on_event(ev),
                    Ok(None) => break,
                    Err(e) => return Err(format!("X event: {e}")),
                }
            }
            while let Ok(cmd) = self.cmd_rx.try_recv() {
                self.apply(cmd);
            }
            self.flush_motion();
            self.flush_beacon();
            self.tick_repeats();
            thread::sleep(POLL_PAUSE);
        }
    }

    fn on_event(&mut self, ev: XEvent) {
        match ev {
            XEvent::XinputRawMotion(e) => {
                let (dx, dy) = raw_xy(&e.valuator_mask, &e.axisvalues_raw);
                self.motion.push(dx, dy);
            }
            XEvent::XinputMotion(e) => {
                // Real (post-acceleration) pointer position: forward any
                // motion accrued since the last send first, then keep
                // only the newest position for the coalesced beacon (see
                // [`BEACON_PERIOD`]) — motion first, resync after, so the
                // session applies deltas then re-anchors, in order.
                self.flush_motion();
                let x = (e.root_x >> 16) as i32;
                let y = (e.root_y >> 16) as i32;
                self.beacon = Some((x, y));
            }
            XEvent::XinputRawButtonPress(e) => self.on_button(e.detail, true),
            XEvent::XinputRawButtonRelease(e) => self.on_button(e.detail, false),
            XEvent::XinputRawKeyPress(e) => {
                if let Some(key) = self.canonical_key(e.detail) {
                    // While the cursor is on a client, Scroll Lock is the
                    // escape hatch: it is consumed here and turned into a
                    // session-level "come home" signal instead of being
                    // forwarded.
                    if self.grabbed && is_escape(key) {
                        log_info!("escape (Scroll Lock) pressed while remote — returning control home");
                        self.send(Message::Escape);
                        return;
                    }
                    self.held.insert(key, Held { down_at: Instant::now(), last_repeat: Instant::now() });
                    self.send(Message::Key { kind: KeyKind::Down, key });
                }
            }
            XEvent::XinputRawKeyRelease(e) => {
                if let Some(key) = self.canonical_key(e.detail) {
                    // Swallow the release of a consumed escape press too
                    // (see the press arm above). If the grab already
                    // released, the stray key-up goes nowhere.
                    if self.grabbed && is_escape(key) {
                        return;
                    }
                    self.held.remove(&key);
                    self.send(Message::Key { kind: KeyKind::Up, key });
                }
            }
            // Anything else (including core events redirected to us by
            // our own grabs) is deliberately ignored: raw events plus the
            // motion beacons are the only streams we act on.
            _ => {}
        }
    }

    fn on_button(&mut self, x11_button: u32, pressed: bool) {
        match buttons::from_x11(x11_button) {
            XButton::Button(canon) => self.send(Message::MouseButton { button: canon, pressed }),
            // A wheel notch is one press/release pair — only the press is
            // a scroll. Forwarding the release as well would make every
            // notch scroll twice on the client.
            XButton::Wheel(dx, dy) => {
                if pressed {
                    self.send(Message::MouseWheel { dx, dy });
                }
            }
            XButton::Ignore => {}
        }
    }

    /// Forward accumulated motion at [`MOTION_PERIOD`] cadence. Called
    /// from the poll loop and before every position beacon, so motion is
    /// never held back longer than one period even when only raw events
    /// arrive (the OS pins the pointer at the screen edge, so raw motion
    /// keeps flowing while position events stop — that continuous flow
    /// is what pushes the virtual cursor across the boundary).
    fn flush_motion(&mut self) {
        let tx = &self.tx;
        self.motion.flush(&mut |dx, dy| {
            let _ = tx.send(Message::MouseMoveRel { dx, dy });
        });
    }

    /// XI2 raw key events carry X keycodes. The standard X11 evdev
    /// mapping is `keycode = evdev + 8`, so the canonical HID usage is
    /// looked up from `keycode - 8`. Unknown keys are dropped (with a
    /// debug log at the caller) rather than sent with a wrong identity.
    fn canonical_key(&self, keycode: u32) -> Option<u32> {
        let evdev = keycode.checked_sub(8)? as u16;
        crate::keys::hid_from_evdev(evdev)
    }

    /// Execute one engine command on this connection.
    fn apply(&mut self, cmd: CaptureCommand) {
        match cmd {
            CaptureCommand::Warp(x, y) => {
                // src_win = NONE warps from the current position.
                let _ = self.conn.warp_pointer(x11rb::NONE, self.root, 0, 0, 0, 0, x as i16, y as i16);
                let _ = self.conn.flush();
            }
            CaptureCommand::CursorVisible(visible) => {
                let res = if visible {
                    xfixes::show_cursor(&self.conn, self.root)
                } else {
                    xfixes::hide_cursor(&self.conn, self.root)
                };
                if res.is_ok() {
                    let _ = self.conn.flush();
                }
            }
            CaptureCommand::Grab(grab) => self.set_grabbed(grab),
            CaptureCommand::IsolateRemote(remote) => {
                // The evdev reader grabs the physical devices at the
                // kernel (X goes fully silent) and starts forwarding;
                // releasing does the reverse and X capture resumes.
                // Also clear the held-key state: once the devices are
                // kernel-grabbed, X never sees the releases of keys that
                // were pressed before (or during) the isolation, so
                // synthesizing repeats for them here would replay stale
                // presses on the client later — the "media keys saved
                // and applied on the client" bug. The evdev reader
                // tracks its own presses instead.
                self.held.clear();
                self.evdev.set_remote(remote);
            }
        }
    }

    /// Grab (or release) the pointer and keyboard on this connection.
    ///
    /// While grabbed, physical input is redirected to us and the local
    /// desktop sees nothing of it; the raw stream — which the session
    /// actually consumes — is unaffected by grabs, so forwarding keeps
    /// working. A failed grab (another client holds one, e.g. a window
    /// manager popup) is logged and tolerated: input still forwards, only
    /// the local-echo suppression is lost until the grab succeeds.
    fn set_grabbed(&mut self, grab: bool) {
        if grab == self.grabbed {
            return;
        }
        let ok = if grab {
            let mask = xproto::EventMask::BUTTON_PRESS
                | xproto::EventMask::BUTTON_RELEASE
                | xproto::EventMask::POINTER_MOTION;
            // Each step fails as `None` on transport or reply errors.
            let pointer = self
                .conn
                .grab_pointer(
                    false, self.root, mask,
                    xproto::GrabMode::ASYNC, xproto::GrabMode::ASYNC,
                    x11rb::NONE, x11rb::NONE, x11rb::CURRENT_TIME,
                )
                .ok()
                .and_then(|c| c.reply().ok())
                .map(|r| r.status == xproto::GrabStatus::SUCCESS);
            let keyboard = self
                .conn
                .grab_keyboard(false, self.root, x11rb::CURRENT_TIME, xproto::GrabMode::ASYNC, xproto::GrabMode::ASYNC)
                .ok()
                .and_then(|c| c.reply().ok())
                .map(|r| r.status == xproto::GrabStatus::SUCCESS);
            match (pointer, keyboard) {
                (Some(true), Some(true)) => true,
                (p, k) => {
                    log_warn!("input grab not acquired (pointer: {p:?}, keyboard: {k:?})");
                    false
                }
            }
        } else {
            let _ = self.conn.ungrab_pointer(x11rb::CURRENT_TIME);
            let _ = self.conn.ungrab_keyboard(x11rb::CURRENT_TIME);
            let _ = self.conn.flush();
            false
        };
        self.grabbed = if grab { ok } else { false };
        if self.grabbed {
            log_debug!("local input grabbed (cursor is on a client)");
        } else if !grab {
            log_debug!("local input released");
        }
    }

    /// Synthesize auto-repeat for physically held keys. Raw events carry
    /// no repeats (they are device transitions only), so clients would
    /// otherwise see a single press for a held key.
    /// Forward the coalesced position beacon at [`BEACON_PERIOD`]
    /// cadence, if one is pending. Called from the poll loop, so a beacon
    /// is never delayed longer than one period after the pointer stops
    /// (the loop wakes every [`POLL_PAUSE`]) — edge parks are confirmed
    /// to the session within ~8 ms even under load.
    fn flush_beacon(&mut self) {
        let Some((x, y)) = self.beacon else { return };
        let now = Instant::now();
        let due = match self.last_beacon {
            Some(t) => now.duration_since(t) >= BEACON_PERIOD,
            None => true,
        };
        if !due {
            return;
        }
        self.last_beacon = Some(now);
        self.beacon = None;
        self.send(Message::MouseMoveAbs { x, y });
    }

    fn tick_repeats(&mut self) {
        if self.held.is_empty() {
            return;
        }
        let now = Instant::now();
        let mut due: Vec<u32> = Vec::new();
        for (key, h) in self.held.iter_mut() {
            if now.duration_since(h.down_at) >= REPEAT_DELAY && now.duration_since(h.last_repeat) >= REPEAT_INTERVAL {
                h.last_repeat = now;
                due.push(*key);
            }
        }
        for key in due {
            self.send(Message::Key { kind: KeyKind::Repeat, key });
        }
    }

    fn send(&self, msg: Message) {
        // The channel is unbounded; the server main loop drains it at its
        // own pace. If the receiver is gone (shutdown), drop the message.
        let _ = self.tx.send(msg);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use x11rb::protocol::xtest::ConnectionExt as _;

    /// The decisive fact behind kernel input isolation: apps that read
    /// XI2 *raw* events (browsers, smooth-scroll terminals like kitty)
    /// receive them even while another client holds a core pointer grab
    /// — core grabs only suppress *core* delivery. XI2 *device* grabs
    /// (XIGrabDevice) are documented to report "only to the grabbing
    /// client"; this test proves that **even they do not suppress raw
    /// delivery** on a real server: while the grabber holds XIGrabDevice
    /// on every device, an observer that selected raw events (exactly
    /// like our capture does) *keeps receiving them*. That is why the
    /// capture switches to kernel grabs ([`crate::evdev_reader`]) while
    /// the cursor is on a client — no X-level grab can silence raw
    /// readers.
    #[test]
    fn xi2_device_grab_does_not_suppress_raw_events_for_other_clients() {
        // Needs a live X server (real cross-client delivery rules); skip
        // silently in headless environments.
        let (Ok((observer, screen_num)), Ok((grabber, _))) = (
            RustConnection::connect(None),
            RustConnection::connect(None),
        ) else {
            eprintln!("skipping: no X server available");
            return;
        };
        let root = observer.setup().roots[screen_num].root;

        // The observer selects raw events exactly like the capture.
        select_input_events(&observer, root).expect("observer selects raw events");

        // Inject XTEST motion (produces raw events, verified below).
        let inject = |c: &RustConnection, n: i32| {
            for i in 0..n {
                let _ = c.xtest_fake_input(6, 0, x11rb::CURRENT_TIME, root, (10 + i) as i16, 10, 0);
            }
            let _ = c.flush();
        };
        fn drain_raw(c: &RustConnection, dur: Duration) -> usize {
            let deadline = Instant::now() + dur;
            let mut n = 0;
            while Instant::now() < deadline {
                match c.poll_for_event() {
                    Ok(Some(XEvent::XinputRawMotion(_))) => n += 1,
                    Ok(Some(_)) => {}
                    Ok(None) => std::thread::sleep(Duration::from_millis(2)),
                    Err(_) => break,
                }
            }
            n
        }

        // Baseline: without a grab the observer sees the injected raw
        // motion (this also proves XTEST produces raw events at all).
        inject(&grabber, 5);
        let baseline = drain_raw(&observer, Duration::from_millis(150));
        assert!(baseline > 0, "XTEST motion should reach the observer (baseline {baseline})");

        // Grab every device with XIGrabDevice and confirm it holds
        // (grabs must succeed for the test to mean anything).
        let mask = [u32::from(XIEventMask::RAW_MOTION)];
        let devices = xinput::xi_query_device(&grabber, DEVICE_ALL).unwrap().reply().unwrap();
        let mut grabbed: Vec<u16> = Vec::new();
        for info in &devices.infos {
            let reply = xinput::xi_grab_device(
                &grabber,
                root,
                x11rb::CURRENT_TIME,
                x11rb::NONE,
                info.deviceid,
                xproto::GrabMode::ASYNC,
                xproto::GrabMode::ASYNC,
                xinput::GrabOwner::NO_OWNER,
                &mask,
            )
            .unwrap()
            .reply()
            .unwrap();
            if reply.status == xproto::GrabStatus::SUCCESS {
                grabbed.push(info.deviceid);
            }
        }
        assert!(!grabbed.is_empty(), "at least one device must be grabbed");
        let _ = grabber.flush();

        // While every device is grabbed, the observer *still* receives
        // raw motion. This is the leak this project exists to close: no
        // X-level grab — core or device — can stop raw-reading apps from
        // reacting to forwarded input. Only kernel isolation can.
        inject(&grabber, 5);
        let during = drain_raw(&observer, Duration::from_millis(150));
        assert!(
            during > 0,
            "raw motion must still reach the observer during a device grab (got {during}) — if the X server now suppresses it, revisit the isolation design"
        );

        // Release everything: raw delivery continues for the observer.
        for id in &grabbed {
            let _ = xinput::xi_ungrab_device(&grabber, x11rb::CURRENT_TIME, *id);
        }
        let _ = grabber.flush();
        inject(&grabber, 5);
        let after = drain_raw(&observer, Duration::from_millis(150));
        assert!(after > 0, "raw motion must resume after ungrab (got {after})");
    }

    #[test]
    fn fixed_point_converts_to_f64() {
        let v = Fp3232 { integral: 3, frac: 0x8000_0000 }; // 3.5
        assert_eq!(fp_to_f64(&v), 3.5);
        let v = Fp3232 { integral: -1, frac: 0 }; // -1.0
        assert_eq!(fp_to_f64(&v), -1.0);
    }

    /// Fp3232 with a given whole value (no fraction).
    fn fp(v: i32) -> Fp3232 {
        Fp3232 { integral: v, frac: 0 }
    }

    #[test]
    fn raw_xy_takes_first_two_axes_positionally() {
        // Classic 2-axis mouse: mask bits 0 and 1, values in order.
        let mask = vec![0b11];
        let values = vec![fp(4), fp(-7)];
        assert_eq!(raw_xy(&mask, &values), (4.0, -7.0));
    }

    #[test]
    fn raw_xy_ignores_scroll_axes_from_multi_valuator_devices() {
        // 4-axis mouse: RelX=0, RelY=1, RelHorizScroll=2, RelVertScroll=3.
        // A wheel notch arrives as a raw motion carrying *only* the
        // vertical scroll valuator. Positionally that value would be
        // taken as dx; mask-walking must yield zero motion.
        let mask = vec![1 << 3];
        let values = vec![fp(120)]; // one vertical notch
        assert_eq!(raw_xy(&mask, &values), (0.0, 0.0));
    }

    #[test]
    fn raw_xy_mixes_motion_and_scroll_in_one_event() {
        // A diagonal move while the wheel ticks: all four axes present.
        // Only Rel X / Rel Y may come out; scroll deltas must be dropped.
        let mask = vec![0b1111];
        let values = vec![fp(3), fp(2), fp(-120), fp(-120)];
        assert_eq!(raw_xy(&mask, &values), (3.0, 2.0));
    }

    #[test]
    fn raw_xy_handles_masks_spanning_multiple_words() {
        // Hypothetical device with axes beyond 32 (word 1, bit 2 = axis
        // 34). XY are still found; the extra axis contributes nothing.
        let mask = vec![1 << 0, 1 << 2];
        let values = vec![fp(9), fp(5)];
        assert_eq!(raw_xy(&mask, &values), (9.0, 0.0));
    }

    #[test]
    fn raw_xy_with_empty_event_is_zero() {
        assert_eq!(raw_xy(&[], &[]), (0.0, 0.0));
        // Values without a mask are never indexed (mask drives the walk).
        assert_eq!(raw_xy(&[0], &[fp(99)]), (0.0, 0.0));
    }
}
