//! The X11 backend (Linux).
//!
//! Three pieces, each with its own X connection so nothing contends:
//!
//! * [`capture::InputCapture`] — a thread that reads **XI2 raw events**
//!   (motion deltas, buttons, keys) straight from the input devices and
//!   forwards them as protocol [`Message`]s. Raw events are generated by
//!   the *hardware*, never by programmatic warps, so warping the local
//!   cursor (park/warp) can never feed phantom motion back into the
//!   session — the exact bug family that plagues other KVMs. The same
//!   thread also performs every cursor *control* action (grab, warp,
//!   hide/show) on its connection, because the client that grabs the
//!   pointer must be the one that warps it. While the cursor is on a
//!   client, pointer and keyboard are grabbed so the local desktop does
//!   not act on the same physical input being forwarded — see
//!   [`capture`] for the details.
//! * [`engine::X11Engine`] — the server's control of its own screen:
//!   clipboard + pointer-position queries on its own connection; cursor
//!   warp/hide/grab delegated to the capture thread via commands.
//! * [`injector::X11Injector`] — the client's control of its own screen:
//!   move the cursor, inject buttons/keys/wheel (XTest), hide the local
//!   cursor while being controlled, read/write the clipboard.

mod buttons;
pub mod capture;
pub mod engine;
pub mod injector;

use std::sync::mpsc::{self, Receiver};
use std::sync::Arc;

use kvmshare_core::client::{Clipboard, Injector};
use kvmshare_core::server::{Engine, Liveness};
use kvmshare_protocol::message::Message;

/// The server-side X11 platform: local input capture + local cursor
/// engine + the standalone clipboard service.
pub struct Server {
    /// Incoming local input events (motion/buttons/keys).
    pub input: Receiver<Message>,
    /// Control of the local cursor.
    pub engine: Box<dyn Engine>,
    /// The local clipboard, on its own lock in the app layer. Split from
    /// the engine on purpose: a clipboard read can block on the
    /// selection owner, and the engine lock serializes cursor motion.
    pub clipboard: Box<dyn Clipboard>,
    /// Liveness heartbeats for the server supervisor; the capture
    /// thread's tick is wired here.
    pub liveness: Arc<Liveness>,
}

impl Server {
    /// Open the X display (default when `None`), start input capture, and
    /// build the engine and the clipboard service.
    pub fn start(display: Option<&str>) -> Result<Self, String> {
        let (cmd_tx, cmd_rx) = mpsc::channel();
        let (input, capture_tick) = capture::start(display, cmd_rx)?;
        let engine = Box::new(engine::X11Engine::new(display, cmd_tx)?);
        let clipboard: Box<dyn Clipboard> = Box::new(injector::X11Clipboard::new(display));
        let liveness = Arc::new(Liveness { capture_tick_ms: capture_tick, ..Default::default() });
        Ok(Self { input, engine, clipboard, liveness })
    }
}

/// The client-side X11 platform: an input injector and the standalone
/// clipboard service (see [`core::client::Clipboard`] for why the
/// clipboard is split from the injector).
pub fn client_injector(
    display: Option<&str>,
) -> Result<(Box<dyn Injector>, Box<dyn kvmshare_core::client::Clipboard>), String> {
    Ok((
        Box::new(injector::X11Injector::new(display)?),
        Box::new(injector::X11Clipboard::new(display)),
    ))
}