//! The X11 backend (Linux).
//!
//! Three pieces, each with its own X connection so nothing contends:
//!
//! * [`capture::InputCapture`] — a thread that reads **XI2 raw events**
//!   (motion deltas, buttons, keys) straight from the input devices and
//!   forwards them as protocol [`Message`]s. Raw events are generated by
//!   the *hardware*, never by programmatic warps, so warping the local
//!   cursor (park/recenter) can never feed phantom motion back into the
//!   session — the exact bug family that plagues other KVMs.
//! * [`engine::X11Engine`] — the server's control of its own screen:
//!   warp the cursor, hide/show it (XFixes), read/write the clipboard.
//! * [`injector::X11Injector`] — the client's control of its own screen:
//!   move the cursor, inject buttons/keys/wheel (XTest), hide the local
//!   cursor while being controlled, read/write the clipboard.

mod buttons;
pub mod capture;
pub mod engine;
pub mod injector;

use std::sync::mpsc::Receiver;

use kvmshare_core::server::Engine;
use kvmshare_core::client::Injector;
use kvmshare_protocol::message::Message;

/// The server-side X11 platform: local input capture + local cursor engine.
pub struct Server {
    /// Incoming local input events (motion/buttons/keys/clipboard polls).
    pub input: Receiver<Message>,
    /// Control of the local cursor and clipboard.
    pub engine: Box<dyn Engine>,
}

impl Server {
    /// Open the X display (default when `None`), start input capture, and
    /// build the engine. Two separate X connections: the capture thread
    /// owns one exclusively, the engine the other.
    pub fn start(display: Option<&str>) -> Result<Self, String> {
        let input = capture::start(display)?;
        let engine = Box::new(engine::X11Engine::new(display)?);
        Ok(Self { input, engine })
    }
}

/// The client-side X11 platform: an input injector.
pub fn client_injector(display: Option<&str>) -> Result<Box<dyn Injector>, String> {
    Ok(Box::new(injector::X11Injector::new(display)?))
}